---
title: Lime School
timezone: America/New_York
collections:
  freshmen-english:
    title: Freshmen English
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
name: Lime School
author:
  name: Emil Sayahi
  "//facebook": your-id
  "//twitter": 
  "/github": 
  "//linkedin": your-id
  "//medium": your-id
  "//tumblr": your-id
  email: emilsayahi@foresthills.edu
google-analytics:
  "//id": 
disqus:
  "/id": 
url: https://limeschool.github.io/
baseurl: 
permalink: "/:year-:month-:day/:title/"
paginate: 5
paginate_path: "/page:num/"
markdown: kramdown
kramdown:
  imput: GFM
nav:
- name: About
  url: "/about"
- name: Archive
  url: "/archive"
- name: Tags
  url: "/tags"
- name: Freshmen English
  url: http://limeschool.cf/freshmen-english/index/
sass:
  sass_dir: _sass
  style: compressed
gems:
- jekyll-seo-tag
- jekyll-paginate
exclude:
- vendor
