# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lime School
email: emilsayahi@foresthills.edu
description: > # this means to ignore newlines until "baseurl:"
    This is just another Jekyll theme.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://limeschool.cf" # the base hostname & protocol for your site
facebook:
github:  https://github.com/limeshool
twitter:

# Build settings
markdown: kramdown

paginate: 3
paginate_path: "page:num"


gems: [jekyll-paginate] 
